# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lab6.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lab6.proto',
  package='lab6Proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nlab6.proto\x12\tlab6Proto\"\"\n\naddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x15\n\x08\x61\x64\x64Reply\x12\t\n\x01\x63\x18\x01 \x01(\x05\"\x1e\n\x0frawimageRequest\x12\x0b\n\x03img\x18\x01 \x01(\x0c\"+\n\nimageReply\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\")\n\x11\x64otproductRequest\x12\t\n\x01\x61\x18\x01 \x03(\x01\x12\t\n\x01\x62\x18\x02 \x03(\x01\"\x1c\n\x0f\x64otproductReply\x12\t\n\x01\x63\x18\x01 \x01(\x01\"\x1f\n\x10jsonimageRequest\x12\x0b\n\x03img\x18\x01 \x01(\t2\x95\x02\n\x08Lab6grpc\x12\x35\n\x05\x64oAdd\x12\x15.lab6Proto.addRequest\x1a\x13.lab6Proto.addReply\"\x00\x12J\n\x0c\x64oDotproduct\x12\x1c.lab6Proto.dotproductRequest\x1a\x1a.lab6Proto.dotproductReply\"\x00\x12\x41\n\ndoRawimage\x12\x1a.lab6Proto.rawimageRequest\x1a\x15.lab6Proto.imageReply\"\x00\x12\x43\n\x0b\x64oJsonimage\x12\x1b.lab6Proto.jsonimageRequest\x1a\x15.lab6Proto.imageReply\"\x00\x62\x06proto3'
)




_ADDREQUEST = _descriptor.Descriptor(
  name='addRequest',
  full_name='lab6Proto.addRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='lab6Proto.addRequest.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='lab6Proto.addRequest.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=59,
)


_ADDREPLY = _descriptor.Descriptor(
  name='addReply',
  full_name='lab6Proto.addReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='c', full_name='lab6Proto.addReply.c', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=82,
)


_RAWIMAGEREQUEST = _descriptor.Descriptor(
  name='rawimageRequest',
  full_name='lab6Proto.rawimageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='lab6Proto.rawimageRequest.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=114,
)


_IMAGEREPLY = _descriptor.Descriptor(
  name='imageReply',
  full_name='lab6Proto.imageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='lab6Proto.imageReply.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='lab6Proto.imageReply.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=159,
)


_DOTPRODUCTREQUEST = _descriptor.Descriptor(
  name='dotproductRequest',
  full_name='lab6Proto.dotproductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='lab6Proto.dotproductRequest.a', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='b', full_name='lab6Proto.dotproductRequest.b', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=202,
)


_DOTPRODUCTREPLY = _descriptor.Descriptor(
  name='dotproductReply',
  full_name='lab6Proto.dotproductReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='c', full_name='lab6Proto.dotproductReply.c', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=232,
)


_JSONIMAGEREQUEST = _descriptor.Descriptor(
  name='jsonimageRequest',
  full_name='lab6Proto.jsonimageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='lab6Proto.jsonimageRequest.img', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=265,
)

DESCRIPTOR.message_types_by_name['addRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['addReply'] = _ADDREPLY
DESCRIPTOR.message_types_by_name['rawimageRequest'] = _RAWIMAGEREQUEST
DESCRIPTOR.message_types_by_name['imageReply'] = _IMAGEREPLY
DESCRIPTOR.message_types_by_name['dotproductRequest'] = _DOTPRODUCTREQUEST
DESCRIPTOR.message_types_by_name['dotproductReply'] = _DOTPRODUCTREPLY
DESCRIPTOR.message_types_by_name['jsonimageRequest'] = _JSONIMAGEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

addRequest = _reflection.GeneratedProtocolMessageType('addRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDREQUEST,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6Proto.addRequest)
  })
_sym_db.RegisterMessage(addRequest)

addReply = _reflection.GeneratedProtocolMessageType('addReply', (_message.Message,), {
  'DESCRIPTOR' : _ADDREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6Proto.addReply)
  })
_sym_db.RegisterMessage(addReply)

rawimageRequest = _reflection.GeneratedProtocolMessageType('rawimageRequest', (_message.Message,), {
  'DESCRIPTOR' : _RAWIMAGEREQUEST,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6Proto.rawimageRequest)
  })
_sym_db.RegisterMessage(rawimageRequest)

imageReply = _reflection.GeneratedProtocolMessageType('imageReply', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6Proto.imageReply)
  })
_sym_db.RegisterMessage(imageReply)

dotproductRequest = _reflection.GeneratedProtocolMessageType('dotproductRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOTPRODUCTREQUEST,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6Proto.dotproductRequest)
  })
_sym_db.RegisterMessage(dotproductRequest)

dotproductReply = _reflection.GeneratedProtocolMessageType('dotproductReply', (_message.Message,), {
  'DESCRIPTOR' : _DOTPRODUCTREPLY,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6Proto.dotproductReply)
  })
_sym_db.RegisterMessage(dotproductReply)

jsonimageRequest = _reflection.GeneratedProtocolMessageType('jsonimageRequest', (_message.Message,), {
  'DESCRIPTOR' : _JSONIMAGEREQUEST,
  '__module__' : 'lab6_pb2'
  # @@protoc_insertion_point(class_scope:lab6Proto.jsonimageRequest)
  })
_sym_db.RegisterMessage(jsonimageRequest)



_LAB6GRPC = _descriptor.ServiceDescriptor(
  name='Lab6grpc',
  full_name='lab6Proto.Lab6grpc',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=268,
  serialized_end=545,
  methods=[
  _descriptor.MethodDescriptor(
    name='doAdd',
    full_name='lab6Proto.Lab6grpc.doAdd',
    index=0,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=_ADDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='doDotproduct',
    full_name='lab6Proto.Lab6grpc.doDotproduct',
    index=1,
    containing_service=None,
    input_type=_DOTPRODUCTREQUEST,
    output_type=_DOTPRODUCTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='doRawimage',
    full_name='lab6Proto.Lab6grpc.doRawimage',
    index=2,
    containing_service=None,
    input_type=_RAWIMAGEREQUEST,
    output_type=_IMAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='doJsonimage',
    full_name='lab6Proto.Lab6grpc.doJsonimage',
    index=3,
    containing_service=None,
    input_type=_JSONIMAGEREQUEST,
    output_type=_IMAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LAB6GRPC)

DESCRIPTOR.services_by_name['Lab6grpc'] = _LAB6GRPC

# @@protoc_insertion_point(module_scope)
